### ISSUE TITLE
Installation requires numpy

### ISSUE THREAD

**Issue by jonrkarr** [RuleWorld/PyBioNetGen#11]
The dependency of the installation on numpy can create problems. Ideally this would be managed by the setup script.

```
Collecting bionetgen
  Using cached bionetgen-0.3.2.tar.gz (9.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l4japc83/bionetgen_55aed50bd983464484fbd01197fbf1e3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l4japc83/bionetgen_55aed50bd983464484fbd01197fbf1e3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gafrizsj
         cwd: /tmp/pip-install-l4japc83/bionetgen_55aed50bd983464484fbd01197fbf1e3/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l4japc83/bionetgen_55aed50bd983464484fbd01197fbf1e3/setup.py", line 2, in <module>
        from bionetgen.core.version import get_version
      File "/tmp/pip-install-l4japc83/bionetgen_55aed50bd983464484fbd01197fbf1e3/bionetgen/__init__.py", line 1, in <module>
        from .core.defaults import defaults
      File "/tmp/pip-install-l4japc83/bionetgen_55aed50bd983464484fbd01197fbf1e3/bionetgen/core/__init__.py", line 4, in <module>
        from .result import BNGResult
      File "/tmp/pip-install-l4japc83/bionetgen_55aed50bd983464484fbd01197fbf1e3/bionetgen/core/result.py", line 2, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bc/0a/12b0cc2800c6027302f8b21d31a8909a7c06000f5ce4d9e73288fd9cc442/bionetgen-0.3.2.tar.gz#sha256=d1f0f908c105890644d0e34691b8808a87080b5d63bfcba296295b0e5431c01d (from https://pypi.org/simple/bionetgen/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ASinanSaglam** [comment]
I was aware of this issue, can you point me to a numpy bootstrapping option in `setup.py` ? I found multiple solutions to this but I'm unsure which one is well tested and stable.

**Comment by jonrkarr** [comment]
I don't think there's a canonical way to do this.

One option is to use pip to install numpy prior to `setuptools.setup` is executed. This works fine in my experience. Something like the following.
```
import setuptools
import sys
sys.subprocess.check_call([sys.executable, '-m', 'pip', 'install' 'numpy'])
setuptools.setup(...)
```

I recommend calling pip via subprocess rather than importing pip because pip doesn't provide a stable API.

**Comment by ASinanSaglam** [comment]
A bit late but b70c3d8b637947de616ae6e059adacdfaee88c44 should address this. Please let me know if it doesn't work on your end, I'll reopen the issue.
